### ISSUE TITLE
F1 Export doesn't include Business

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Slingshot#49]
I'd like to add business to the F1 Export. However, slingshot as a whole doesn't support business records.  So that also needs to be added to core / and bulk import in Rock.  I wanted to create the issue here to see if anyone else has already started work on this. @mkinyon @dcs619 specifically.

**Comment by edmistj** [comment]
We've been discussing that internally and have been planning to add it. Our timeline though isn't until v9 is out.

**Comment by JoshuaMaiorino** [comment]
Okay, I'm happy to work on it.  If you have any notes, or ways you want it done.  I was planning on just adding record type to the person entity in slingshot core.  And running it the same way. Not sure if that's the best way or not though.

**Comment by edmistj** [comment]
If you want to take a stab at a PR then feel free. Here's the only notes we have on it:

Since there are many many similarities between the person, family, and group member slingshot files, 

## business.csv   
`Id,Name,RecordStatus,InactiveReason,Email,EmailPreference,CampusId`

## business-address.csv 
`BusinessId,Street1,Street2,City,State,PostalCode,Country,Latitude,Longitude,AddressType`

## business-phone.csv 
`BusinessId,PhoneType,PhoneNumber,IsMessagingEnabled,IsUnlisted`

## business-contact.csv 
`PersonId,BusinessId`

**Comment by JoshuaMaiorino** [comment]
Okay,  Sounds great.  Thank you.

**Comment by JoshuaMaiorino** [comment]
I've added Business Attributes as well.

**Comment by edmistj** [comment]
Do you have an eta you're working to?

**Comment by JoshuaMaiorino** [comment]
I'd like to have everything implemented by Friday May 3rd
